version: '3.4'

services:
  postech8soat.fastorder.webapi:
    image: ${DOCKER_REGISTRY-}postech8soatfastorderwebapi
    build:
      context: .
      dockerfile: src/Postech8SOAT.FastOrder.WebAPI/Dockerfile
    ports:
      - '57398:57398'
      - '57399:57399'
    environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:57399;http://+57398
        - ASPNETCORE_Kestrel__Certificates__Default__Password=fiap@123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/fastorder.pfx  
    volumes:
        - ./certs:/app/certs
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver-fc'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "tech#2024"
    volumes:
    - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'
    expose:
      - 1433