apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-dep
  labels:
    app: sqlserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-dep
  template:
    metadata:
      labels:
        app: sqlserver-dep
    spec:
      containers:
      - name: sqlserver-dep
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        envFrom:
        - configMapRef:
            name: fo-db-configmap
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: kuku-pvc